### ISSUE TITLE
Par ito na po ung Issue

### ISSUE THREAD

**Issue by Wink1992** [lloricode/lloricode.github.io#1]
![issue1](https://user-images.githubusercontent.com/30583058/29012101-8888450c-7b6b-11e7-986d-225b82dd0a0d.jpg)

lats commit
 manage department with faculty and students.

    Signed-off-by: Lloric Mayuga Garcia <emorickfighter@gmail.com>

**Comment by lloricode** [comment]
Issue related https://github.com/lloricode/e-ttendance-laravel/issues/2
ok ok will fix this :), pero wrong project issue lang :D
